feat: clearly distinguish select and hover states
bpmn-io/diagram-js pull request #640
Opened 2022-05-18 09:51 UTC by nikku

This proposes a clear distinction between select and hover states:

![capture uBoe56_optimized](https://user-images.githubusercontent.com/58601/169010686-13fd2c6e-b1da-40f1-b0ed-affef773a7ce.gif)

----

There is an alternative on the deck (2px solid outline for select, rather than 1px). I'd ask you for your quick opinion here @philippfromme @andreasgeier @christian-konrad:

![capture tMpD5L_optimized](https://user-images.githubusercontent.com/58601/169011156-b441554d-c587-4fb3-9668-4e40b3c350ee.gif)

I'm personally in favor of the minimal change (just making the outline solid for selected elements). As you see from the screens above it is nicer on other UI elements (resizers, connector draggers) that we have right now.

2022-05-18 10:50 UTC, philippfromme commented
In my opinion we should not only increase the line width but also the size of the handles (resize, segment move), which are smaller then bendpoint move handles. I proposed this years ago.

![brave_oFzsDMFUMP](https://user-images.githubusercontent.com/7633572/169022181-d15a7281-0b9f-418f-b193-3f69d2098f31.gif)

2022-05-18 12:35 UTC, andreasgeier commented
I'd go with 2px. Consider, that single select is the default case and it should help to better see/find the selected element. Particularly in case of clicking on an error message references.

Please avoid a hover state on selected elements. It's not common and I believe it is confusing.

2022-05-18 12:37 UTC, nikku commented
@philippfromme You have your adjustments on a branch?

2022-05-18 12:44 UTC, philippfromme commented
@nikku https://github.com/bpmn-io/diagram-js/tree/philipp-styles 😉

2022-05-18 13:14 UTC, christian-konrad commented
2px looks better. 1px makes sense for high-precision drawing tools (adobe, affinity, sketch...), but for a rapid modeling tool, quick distinguishability and clickability is more important.

2022-05-18 13:16 UTC, christian-konrad requested changes

2022-05-18 13:16 UTC, christian-konrad commented on assets/diagram-js.css
>    stroke-width: 1px;
2px as discussed

2022-05-18 18:27 UTC, nikku commented
I'll provide another version that incorporates @philippfromme styles. If we go for https://github.com/bpmn-io/diagram-js/pull/640#issuecomment-1130003235, more general clarity on our UI controls helps.

2022-05-18 18:38 UTC, nikku commented
> 
2px looks better. 1px makes sense for high-precision drawing tools (adobe, affinity, sketch...), but for a rapid modeling tool, quick distinguishability and clickability is more important.

Visual sizing has no impact for `clickability`. This is really about what we want to be, a happy looking sketching tool, or a slight less in your face app. Miro for example goes for 1px, no problem.

2022-05-19 08:16 UTC, nikku commented
Accounting for @philippfromme feedback but also taking into consideration other drawing apps I've reworked this PR:

* Outline is solid, if it is shown
* Hover outline is gone (no-one has it)
* Handles are not transparent, and sized appropriately
* No two pixel border, as this looks toyish (and other tools don't have it, too)

---

I've considered the following tools for comparison:

* Google Slides
* Excalidraw
* Miro

2022-05-19 08:28 UTC, currandwyer commented
I think this is looking great! Cool that we're working on it. One question for you @nikku - why don't we ease the corners of the selection boxes? I think this looks much more refined, given that almost everything being selected also has rounded corners. All we would need to do is decide on a different behavior for pools, which seems doable to me.

2022-05-19 08:48 UTC, philippfromme commented
> why don't we ease the corners of the selection boxes?

@currandwyer  Do you mean border radius?

2022-05-19 08:52 UTC, nikku commented
@philippfromme That is a minimal one, right? I'll give it a shot and report back how that looks like.

2022-05-19 08:56 UTC, currandwyer commented
Yeah @philippfromme I think even just having 1-2 px corner radius is nice - it's subtle, but it softens the look a bit, and shows that you thought about it. By the way, in Operate we already have a relatively large corner radius:
<img width="1746" alt="Screen Shot 2022-04-20 at 19 21 02" src="https://user-images.githubusercontent.com/11223953/169254715-2726bf07-550e-4710-9413-ed4568813108.png">

2022-05-19 09:04 UTC, nikku commented
@currandwyer Thanks for the operate screen. Does the user interact with Participants there? How does operate handle selection on DMN DRD diagrams (with decisions and text annotations)?

![image](https://user-images.githubusercontent.com/58601/169256488-de0ecc55-a70f-440b-aede-fc296fbf367f.png)

2022-05-19 09:09 UTC, nikku commented
And as we're on it, here is a "bold selection outline" (3px radius) variation: 

![capture mMaabe_optimized](https://user-images.githubusercontent.com/58601/169257510-45adb988-02b7-46ef-b54a-15240444bff8.gif)

2022-05-19 09:15 UTC, nikku commented
One thing we have to consider is the newly introduced multi-selection box (https://github.com/bpmn-io/diagram-js/pull/587).

2022-05-19 09:20 UTC, nikku commented
Marked as draft as we clearly still discover what we want to do :wink:

2022-05-19 09:21 UTC, nikku commented
Miro does something else interesting which we'll need to account for now, too (https://github.com/bpmn-io/diagram-js/pull/587). They color elements differently: Distinguish primary from secondary selection:

![capture a51Lxn_optimized](https://user-images.githubusercontent.com/58601/169259642-fda2b63f-9e7c-4060-b4df-0e5b9674c171.gif)

2022-05-19 09:25 UTC, philippfromme commented
> What do you think?

Minimal border radius (2-3px) would be my choice. If it's too big it looks weird and distracting.

2022-05-19 09:27 UTC, philippfromme commented
> And as we're on it, here is a "bold selection outline"

I'm a fan of 2px stroke width. It looks so satisfying. 😋

2022-05-19 09:28 UTC, philippfromme commented
> @currandwyer Thanks for the operate screen. Does the user interact with Participants there? How does operate handle selection on DMN DRD diagrams (with decisions and text annotations)?

This is why I'd say minimal border radius is fine. Due to the padding it would never overlap the element.

2022-05-19 09:31 UTC, currandwyer commented
I think that 3px radius is great! @nikku I wasn't being clear about Operate - I am wondering why it's done differently. To me, it seems like it should be aligned.

2022-05-19 13:22 UTC, nikku commented
Proposal for solution, incorporating modern hover vs. select interaction; clearly distinguishable (+ rounded nice to the eye) selection box + multi-select aware:

![capture WUR6jb_optimized](https://user-images.githubusercontent.com/58601/169303246-28c23f66-e46e-4be4-b1e2-9ce7affea552.gif)

2022-05-19 13:39 UTC, philippfromme commented
> Proposal for solution, incorporating modern hover vs. select interaction; clearly distinguishable (+ rounded nice to the eye) selection box + multi-select aware:

I'm a fan. 💯

2022-05-19 14:32 UTC, philippfromme commented
I was wondering, shouldn't the outline always be on top? 🤔 

![image](https://user-images.githubusercontent.com/7633572/169320885-5f592b6f-80db-4555-861e-17065a973192.png)

2022-05-19 15:54 UTC, christian-konrad commented
@nikku  is it possible to have the outline thickness be fixed, so not to scale with the canvas when you zoom?

2022-05-19 15:59 UTC, christian-konrad commented
@nikku interesting thought to get rid of the hover outline at all, this solves many problems with multi-select.
But, would it be possible then to turn the cursor into a drag cursor (like in Google Slides / Excalidraw)
(Just a thought, I am not even sure if I like it)

2022-05-19 18:26 UTC, nikku commented
> @nikku is it possible (and to what cost) to have the outline thickness be fixed, so not to scale with the canvas when you zoom?

Not easily possible.

> But, would it be possible then to turn the cursor into a drag cursor. 

When exactly? We could do it. But I don't miss it (and no-one ever did).
It would also cause conflicts, i.e. in places where you could both start dragging, but also direct editing via double click. TLDR: Let's not optimize it in this PR :wink:

2022-05-19 18:36 UTC, nikku commented
> I was wondering, shouldn't the outline always be on top? thinking Like, not covered by the boundary event.

Let us follow up with this in a new issue @philippfromme.

I've checked other tools and that is exactly how they do it. Our multi-select outline also works like this: 

![image](https://user-images.githubusercontent.com/58601/169374834-68010ad8-0420-4d8e-b49b-80d3d101c841.png)

2022-05-20 06:44 UTC, philippfromme commented
> Let us follow up with this in a new issue @philippfromme.

👍🏻

2022-05-20 08:31 UTC, christian-konrad commented
Just found this bug while testing, which could be caused by this https://github.com/bpmn-io/bpmn-js/issues/1657

2022-05-20 08:45 UTC, christian-konrad commented
I am not 100% happy with having no hover state anymore, but as this solution solves current problems, please move forward with it.
Reconsider hovering if a designer comes up with it and good reasoning.
(There isn't even a real best practice there, there are vector, drawing, model etc tools with and without hover states)

2022-05-20 08:48 UTC, christian-konrad approved these changes

2022-05-20 09:08 UTC, nikku commented
Potential follow up once we got this merged (https://github.com/bpmn-io/diagram-js/pull/643), incorporating @christian-konrad earlier comment (https://github.com/bpmn-io/diagram-js/pull/640#issuecomment-1131903966).

2022-05-23 12:39 UTC, nikku commented
@philippfromme As discussed, please leave this.

2022-05-23 12:56 UTC, nikku commented
Hahaha. leave you review :).

2022-05-23 12:57 UTC, philippfromme approved these changes
This is such a neat package of improvements! 🏅 I love it!

2022-05-23 13:12 UTC, merged