Replace popup menu with new UI
bpmn-io/diagram-js pull request #687
Opened 2022-11-02 08:24 UTC by smbea

Incorporates a reworked popup menu UI based on the [create/append anything prototype](https://github.com/bpmn-io/bpmn-js-connectors-extension).

This can be tested with: 

```
npx @bpmn-io/sr bpmn-io/bpmn-js#develop -l bpmn-io/diagram-js#replace-popup-menu
```

Note: to see a draft of the e2e result you can use this [bpmn-js branch](https://github.com/bpmn-io/bpmn-js/tree/wip-test-popup-menu) 

## Key Changes

### New features
* Menu title
* Search
* Entry options: description, documentation url, group title
* Configurable width

### Behaviour changes
* popup menu exists outside of the canvas

### Breaking changes

* Overall UI (will not affect standard popup menus but might affect UI of menus with CSS customisations on top)
* New class `djs-parent` added to canvas root (`.djs-container`) and popup menu root 
  

## Screenshots (directly after update vs what will look like after adjusting bpmn-js)

#### Replace
<div>
<img width="230" alt="Screenshot 2022-11-14 at 10 57 42" src="https://user-images.githubusercontent.com/25825387/201631510-865b29cc-eb3e-4b95-b3a6-60b73ec6cb89.png">
<img width="300" alt="Screenshot 2022-11-08 at 22 05 09" src="https://user-images.githubusercontent.com/25825387/201632024-fa5e22da-0606-45e1-b3e0-166c86543b13.png">
</div>

#### Align
<div>
<img width="200" alt="Screenshot 2022-11-14 at 10 57 59" src="https://user-images.githubusercontent.com/25825387/201632000-8839216b-4f65-493c-9165-534fa2e20ebe.png">
<img width="200" alt="Screenshot 2022-11-14 at 11 05 35" src="https://user-images.githubusercontent.com/25825387/201632514-0d5e8aec-8e6e-4aed-8053-85989e1c758c.png">
</div>

----

Closes #686

2022-11-03 15:30 UTC, philippfromme commented
What's the state of this pull request? Looking at the comments in https://github.com/bpmn-io/diagram-js/issues/686 I'm not sure which ones have been addressed.

2022-11-03 16:14 UTC, philippfromme commented
Do we want the search bar to be present in the popup menu for alignment?

![image](https://user-images.githubusercontent.com/7633572/199774742-03ab2752-5bd2-4c9e-9a4d-59bf9f1a8542.png)

2022-11-07 13:31 UTC, philippfromme commented
> There are some configurable options that can be set when popupMenu is opened (in bpmn-js) and being searchable is one of them.

Is there a bpmn-js branch showing the usage of these options end-to-end?

2022-11-08 08:59 UTC, philippfromme reviewed
I found two things:

1. Increasing the `min-width` of the replace menu would prevent the width jumping when using the search

![brave_PsEkMyurX3](https://user-images.githubusercontent.com/7633572/200520249-224839a0-ff29-4826-bc7e-de861b7e9e99.gif)

2. The align menu doesn't look right; is this intended?

![brave_8gpCpErzl6](https://user-images.githubusercontent.com/7633572/200520563-d19d8aac-cc40-4b0a-89f3-27515f647d51.gif)

2022-11-08 11:11 UTC, philippfromme commented
> Actually in mine, I don't event get the last 2 options for some reason:

I think the bottom ones are [distribute](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/distribute-elements/DistributeElementsMenuProvider.js) while the ones at the top are align.

2022-11-08 16:51 UTC, nikku commented
We should use [the sketched UI](https://bpmn-io.github.io/bpmn-js-connectors-extension/?aa=1) as a reference (with regards to paddings / margins) and I'm sure we'll be able to adjust for "no search", "no-header" in the same spirit.

Happy to review this if you ping me @smbea once you feel like this is ready for review / stabilized UI wise.

2022-11-09 07:10 UTC, nikku commented
Thanks @smbea for the context. I'll give it a review today.

2022-11-09 12:49 UTC, nikku commented
I've scheduled a session to finalize our diagram-js-ui integration, together with @barmac @smbea and @philippfromme.

2022-11-11 09:24 UTC, nikku requested changes
Looks like great progress overall.

I love that you also tested internals ("the components"). Overall focus for tests shall remain the `PopupMenuSpec` though.

Some remarks:

* Do we want to keep existing classes (where they continue to fit)? Happy to ditch, but we should be explicit about this in the PR description; this is going to be a potential breaking change, and we need to document it.
* Do we want to keep the ability to show images in header entries?
* Do we want to keep existing grouping features? If not we must document an appropriate replacement ("categories")?

2022-11-11 09:24 UTC, nikku commented on assets/diagram-js.css
> +.djs-popup .title {
Do we want to keep the existing class names (where possible?)

2022-11-11 09:24 UTC, nikku commented on test/spec/features/popup-menu/PopupMenuSpec.js
> -import testImage from './resources/a.png';
Any reason we removed these tests? Is the capability gone now?

2022-11-11 09:24 UTC, nikku commented on assets/diagram-js.css
> +  position: fixed;
Should check formatting here.

2022-11-11 09:24 UTC, nikku commented on assets/diagram-js.css
> +  --color-white: #fff;
Should we re-use colors defined globally here or move these colors to the global scope?

I'd love to move variable definitions to the global scope, too:

https://github.com/bpmn-io/diagram-js/blob/develop/assets/diagram-js.css#L5

+ prefix popup styles there with `--popup-`

2022-11-11 09:24 UTC, nikku commented on test/spec/features/popup-menu/PopupMenuSpec.js
> +      expect(domClasses(container).has('djs-popup-parent')).to.be.true;
We could make these tests more robust to verify that `domQueryAll('djs-popup', container)` returns a single element.

2022-11-11 09:24 UTC, nikku commented on test/spec/features/popup-menu/PopupMenuSpec.js
> -      popupMenu.registerProvider('item-menu', {
Did we remove grouping? Or was it superceeded by something?

2022-11-11 09:24 UTC, nikku commented on test/spec/features/popup-menu/PopupMenuSpec.js
> -        popupMenu.registerProvider('group-menu', {
Did we remove grouping? Or was it superceeded by something?

2022-11-11 09:24 UTC, nikku commented on test/spec/features/popup-menu/PopupMenuSpec.js
> -    it('should add standard class to entry', inject(function(popupMenu) {
We could consider to restore that capability.

2022-11-11 09:24 UTC, nikku commented on test/spec/features/popup-menu/PopupMenuSpec.js
> -    it('should update the popup menu, when it is opened again' , inject(
Why did we remove this?

2022-11-11 09:24 UTC, nikku commented on test/spec/features/popup-menu/PopupMenuSpec.js
> -    it('should throw an error, if the id of a header entry is not set', inject(
Why did we remove this?

2022-11-11 09:24 UTC, nikku commented on test/spec/features/popup-menu/PopupMenuSpec.js
>      it('should open within bounds above', inject(function(popupMenu, canvas) {
We don't need the canvas anymore I believe.

2022-11-11 09:24 UTC, nikku commented on test/spec/features/popup-menu/PopupMenuSpec.js
>        function(popupMenu, canvas) {
We don't need the canvas anymore I believe?

2022-11-11 09:42 UTC, nikku commented
Thanks for https://github.com/bpmn-io/diagram-js/pull/687#issuecomment-1311460885 :tada:.

Would be really good if we could keep existing tests where we keep compatibility.

2022-11-11 17:56 UTC, nikku commented on assets/diagram-js.css
> +  --color-white: #fff;
Got cha! Maybe we find a way to re-use these styles / variables regardless, i.e. introduce a `djs-parent` selector that provides them to different roots (popup-menu + djs-container)?

2022-11-14 09:43 UTC, nikku submitted a review, later dismissed
I was not able to do a full review of the latest changes, but did already go ahead and rebase the commit on top of latest develop.

@smbea Could you go ahead and create a CHANGELOG entry for the upcoming changes + populate the PR description with new changes:

* A screenshot to show the new styling
* Documentation of breaking changes (introduction of `.djs-parent` class), new replace menu behavior, new capabilities (search, title, ...).

We'd need that to ship this change.

2022-11-14 22:07 UTC, nikku reviewed
I'm done, after all. Looks awesome. The `PopupMenuSpec` is a great sentiment of not breaking existing contracts (unnecessarily).

----

Added the following changes on top:

* reorganized contribution -> first shared `parent`, then popup menu
* only render search if actually needed
* test teardown (PopupMenuComponent)
* global ESC key binding (without search!)
* recycling of state + callbacks (https://github.com/bpmn-io/diagram-js/pull/687/commits/5e0c57b11797aecbf2a577fae686127f1c49eacf)


From https://github.com/bpmn-io/diagram-js/pull/687/commits/2fcdb7dd5e286e464da2b77b22881619c41893de on I simplified the tests / brought them back to the original form with the purpose to have a functional DIFF in place. That allowed me to find the following not yet documented breaking change:

* `.djs-popup-header .entry` is now `.djs-popup .header .header-entry` => We could decide to restore the original classes (does not hurt?)
  
It also helped me find that `should only render body if entries exist` spec is removed. Shall we add a replacement?

---

All test formatting fixes can be squashed together or dropped as you wish.

2022-11-15 08:49 UTC, merged